sudo: false

language: php

php:
    - 5.6
    - 7.0

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0 CF7=https://downloads.wordpress.org/plugin/contact-form-7.4.9.zip
    - WP_VERSION=nightly WP_MULTISITE=0 CF7=https://downloads.wordpress.org/plugin/contact-form-7.4.9.zip

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
        composer global require "phpunit/phpunit=4.8.*"
      else
        composer global require "phpunit/phpunit=5.7.*"
      fi
    fi

script:
  - phpunit
